### ISSUE TITLE
create template for feature-issue

### ISSUE THREAD

**Issue by sanchis** [sanchis/Madhardware#13]
Create a basic template to submit feature and issue

**Comment by 96RadhikaJadhav** [comment]
@sanchis  Can I work on it?

**Comment by sanchis** [comment]
Sure

**Comment by sanchis** [comment]
Close with #17

**Comment by sanchis** [comment]
The atuoamtic assignment of the labels does not work correctly. For bug type it should automatically assign bug type.
The same error occurs for feature.
