### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by 96RadhikaJadhav** [sanchis/Madhardware#18]

**Comment by sanchis** [comment]
Not work for me. I think the name for the template is incorrect.
Docs: [https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

**Comment by sanchis** [comment]
Closed with #24
